services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solver_api
    restart: unless-stopped
    ports:
      - "${PORT:-8083}:${PORT:-8083}"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solver_worker
    restart: unless-stopped
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=2
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WEBHOOK_URL=http://api-vn:8082/capacity-planning/complete
      - PORT=8083
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
